name = "marchello-sciortino"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[vars]
INSTAGRAM_BUSINESS_ACCOUNT_ID = "17841400436172857"

[[r2_buckets]]
binding = "CONTACT_ATTACHMENTS"
bucket_name = "marchello-contact-attachments"
